CBIIT/bento-icdc-frontend

src/utils/env.js

So local environment will work properly.

Make environmental variables take precedence over injectedEnv.js

---

graphql/icdc-doc.graphql
graphql/icdc.graphql
graphql/icdc_queries.graphql

All count queries now return a GroupCount type
Added case_ids parameter to studiesByProgram query
Updated schema version

Standardized count return types

---

graphql/icdc-doc.graphql
graphql/icdc.graphql
graphql/icdc_queries.graphql

Added "FileID", "StudyInfo", "ProgramStudies" types
Added missing "file_name" property to "FileInList" type
Added "files: [FileID]" to "SampleOverview" type
Reverted previous change to "studiesByProgram" by removing the "case_ids" parameter
Updated "sampleOverview" and "sampleOverviewDesc" to return array of file ids
Added query "programsAndStudies"
Updated schema version

programsAndStudies and type changes

---

src/components/Layout/LayoutView.js

add CRDC nav Bar

---

graphql/icdc-doc.graphql
graphql/icdc.graphql
graphql/icdc_queries.graphql

Added "files" properties in return dataset of caseOverview and caseOverviewDesc.

Updated caseOverviewPaged Queries to include file uuids

---

config/webpack.config.js
public/injectEnv.js
src/bento/caseDetailsData.js
src/bento/navigationBarData.js
src/components/Breadcrumb/BreadcrumbView.js
src/components/GridWithFooter/GridView.js
src/components/GridWithFooter/customFooter.js
src/components/GridWithFooter/index.js
src/components/Header/HeaderView.js
src/components/Layout/LayoutView.js
src/components/NavBar/NavBarView.js
src/components/Snackbar/Snackbar.js
src/components/Snackbar/index.js
src/components/Stats/pageSpecificStatsController.js
src/pages/caseDetails/caseDetailsController.js
src/pages/caseDetails/caseDetailsView.js
src/pages/caseDetails/fileTable.js
src/pages/caseDetails/sampleFileTable.js
src/pages/dashboardTab/store/dashboardReducer.js
src/themes/dark.js
src/themes/icdcLight.js
src/themes/light.js
src/utils/utils.js

Add case detail page and update page header
Page Header depends on bento-tool PR.

Add case detail page and update page header

---

public/index.html
src/bento/caseDetailsData.js
src/bento/dashboardData.js
src/bento/globalFooterData.js
src/bento/studiesData.js
src/pages/studies/studiesView.js

Bento-944 Minor Changes

---

src/bento/fileCentricCartWorkflowData.js
src/pages/fileCentricCart/cartView.js

1) Download Manifest
2) Pagination now working
3) Sorting now working

Fixed Bugs In Cart

---

graphql/icdc-doc.graphql
graphql/icdc.graphql
graphql/icdc_queries.graphql

Updated schema for Bento-992

---

src/bento/caseDetailsData.js
src/bento/programDetailData.js
src/bento/studiesData.js
src/bento/studyDetailsData.js
src/bento/tableDownloadCSV.js

update file name while downloading CSV

file name update

---

src/components/serverPaginatedTable/components/CSVDownloadCustomToolbar.js

css fix for download btn position

Bento 1709

---

src/bento/fileCentricCartWorkflowData.js
src/pages/fileCentricCart/cartView.js

Added a help icon by the user comments textarea on the cartView page to provide more guidance to end users.

added user comments help tooltip to cartView

---

src/bento/navigationBarData.js

minor padding adjust of menu items

adjust right padding

---

src/bento/dashboardTabData.js
src/pages/dashboardTab/components/tabView.js

set properties to hide the 'case id' from view columns

hide 'Case Id' column in hide/show checkbox 

---

public/index.html

 drop down detach and display fix implemented from bento

---

src/pages/fileCentricCart/utils.js

Cart Comment Section writes to wrong cell (fix implemented from bento)

---

src/bento/fileCentricCartWorkflowData.js
src/pages/dashboardTab/components/tabView.js
src/pages/fileCentricCart/cartView.js
src/utils/columnsUtil.js

implement similar fix as in dashboard component to cart component

remove case id from cart component view column check box

---

src/bento/programData.js

1. img for PCCR streamline 
2. img for PCCR study detail

PCCR program img

---

src/bento/dashboardData.js

ICDC-1741_2

---

graphql/icdc-doc.graphql
graphql/icdc.graphql
graphql/icdc_queries.graphql

Minor change bases on model change.

Renamed individual to canine_individual based on model change.

---

src/pages/dashboardTab/store/dashboardReducer.js

get accession id after user clear all the filters

clear all filter removing the accession id

---

src/bento/dashboardData.js
src/bento/dashboardTabData.js

update color code as required by 508 compliance

color update for tabs

---

src/pages/fileCentricCart/components/body/cartTableThemeConfig.js

ICDC-1756_New

---

src/pages/dashboardTab/components/tabView.js

tooltip badge and tab rendering error fix

ICDC-1702_1

---

graphql/icdc-doc.graphql
graphql/icdc.graphql
graphql/icdc_queries.graphql

Added Type "UnifiedCounts"
Added Query "unifiedViewData"

Schema Update 1.1.0

---

package.json
src/pages/dashboardTab/store/dashboardReducer.js

fixed in bento component
code revert

icdc-1814 set default selection

---

src/bento/fileCentricCartWorkflowData.js

Add sample id to my files table

ICDC-1829_1

---

src/bento/tableDownloadCSV.js

Add sample id to my files csv download

ICDC-1829_2

---

src/components/serverPaginatedTable/serverPaginatedTable.js

ICDC-1891 - Source and merge code for Bento table fixes
ICDC - 1788 -FIXED IN BENTO - Incorrect Number of rows after filtering in Cases View.
ICDC - 1728 - FIXED IN BENTO - Add Remove columns do not persist , after we sort

serverPaginatedTable bento fix import

---

graphql/icdc-doc.graphql
graphql/icdc.graphql
graphql/icdc_queries.graphql

Changed individual_id fields to add paddings.

Added paddings (leading zeros) to individual_ids.

---

src/bento/navigationBarData.js

- Implemented Change Log Changes.

Test change-log

---

src/pages/dashboardTab/dashboard.js

ICDC-1916_1

---

src/components/SideBar/SideBarView.js
src/pages/dashboardTab/dashboard.js

Reverts CBIIT/bento-icdc-frontend#298

Revert "Fixed Sapce Issue."

---

src/pages/dashboardTab/components/tabView.js

1. move unifiedViewFlag from CustomDataTable component to customLink
2. create separate method to display all the columns for cases tab.

Icdc 1989 - display all columns for cases tab

---

src/pages/study/views/SampleProfile.js

icdc_2042 Sample profile set max bar width

icdc_2042 sample profile - set max bar width

---

src/components/SideBar/SideBarView.js
src/pages/dashboardTab/components/tabController.js

display correct data on unifiedView page
icdc_2033 - display correct data on unified view page

icdc_2033 display correct data on unified view page

---

graphql/icdc.graphql
graphql/icdc_queries.graphql

add missing columns in the sorting query
add missing columns in the sorting query

icdc_1990 and 2032

---

src/bento/tableDownloadCSV.js

The column Format displays as File Format in CSv download in Dashboard Files tab

csv download

---

src/pages/caseDetails/components/multiStudyCases.js

icdc_2089 text overlapping issue fix

icdc_2089 text overlapping issue fix

---

src/pages/caseDetails/components/multiStudyCases.js

Multistudy D-QA

---

src/pages/caseDetails/components/multiStudyCases.js

ICDC-2095_2

---

graphql/icdc.graphql
graphql/icdc_queries.graphql
src/bento/studyDetailsData.js
src/pages/study/studyDetailController.js

1. update cypher and graphql query - fetch study detail by accession_id or study_designation
2. replace alias url (identifiers.org) with correct url

Icdc 2072 retrieve study detail using alias url 

---

src/bento/studyDetailsData.js
src/pages/study/studyDetailView.js
src/pages/study/views/ArmsAndCohort.js
src/pages/study/views/Overview.js
src/pages/study/views/StudyFiles.js

add tabs for ArmsAndCohort and Study Files

Icdc 2105 add tabs for ArmsAndCohort and Study Files

---

src/pages/study/views/ArmsAndCohort.js
src/pages/study/views/Overview.js

display proper content for pending studies

icdc_2105 display proper content for pending studies

---

src/bento/studyDetailsData.js
src/pages/study/studyDetailController.js

icdc_2072 query fix

---

src/pages/dashboardTab/dashboard.js

Add padAngle to Sunburst component (508 compliance)

Add padAngle to Sunburst component

---

src/pages/study/views/SampleProfile.js

icdc_2122 text update

---

src/pages/study/views/SampleProfile.js

icdc_2134 - Text update

---

package-lock.json
package.json

update latest bento version

---

src/components/Stats/StatsView.js
src/pages/caseDetails/caseDetailsView.js

1. subtract study file count from total files count
2. set study file count to zero for case detail page
1. subtract study file count from total files count
2. set study file count to zero for case detail page

Icdc 2107 hot fix

---

src/bento/studyDetailsData.js
src/components/GridWithFooter/tableThemeConfig.js
src/pages/study/views/ArmsAndCohort.js
src/pages/study/views/StudyFiles.js

adjust table style in study details page

icdc_2139 update table style

---

package-lock.json
package.json
src/bento/studyDetailsData.js
src/pages/study/views/SampleProfile.js

icdc 2088 sample profile histogram code refactor

---

src/pages/dashboardTab/components/tabController.js
src/pages/dashboardTab/components/tabView.js
src/pages/dashboardTab/store/dashboardReducer.js

unified view - add selected files to cart from study tab

multi study view add study files to cart

---

graphql/icdc-doc.graphql
graphql/icdc.graphql
graphql/icdc_queries.graphql
src/bento/tableDownloadCSV.js

add histology cytopathology in extended metadata

icdc_2143 add histology cytopathology in extended metadata

---

src/pages/fileCentricCart/cartView.js
src/pages/fileCentricCart/components/footer/cartFooter.js

https://github.com/CBIIT/bento-frontend/pull/411
myChart pagination fix
code refactor

icdc_2087 fix by myCart table refactor

---

graphql/icdc-doc.graphql
graphql/icdc.graphql
graphql/icdc_queries.graphql
src/bento/tableDownloadCSV.js

add 'matching cases' to extended metadata for case file and my file download
add 'matching cases' to extended metadata for case file and my file download

icdc_2181 and icdc_2182

---

src/components/serverPaginatedTable/serverPaginatedTable.js

Render missing style to the hyperlink in dashboard

icdc 2231 update column state to current props value

---

graphql/icdc-doc.graphql
graphql/icdc.graphql
graphql/icdc_queries.graphql

Biobank Filtering

---

src/pages/study/views/Publication.js

hide link icon in the absence of pubmed or DOI id

icdc_2238 hide link icon in the absence of pubmed or DOI id

---

src/components/ProgramCard/__test__/programCard.test.js
src/components/ProgramCard/programCard.js

programCard test

---

graphql/icdc.graphql
graphql/icdc_queries.graphql

Added missing comma to UnifiedViewData

---

src/bento/fileCentricCartWorkflowData.js
src/components/serverPaginatedTable/serverPaginatedTable.js
src/pages/fileCentricCart/cartController.js
src/pages/fileCentricCart/cartView.js
src/pages/fileCentricCart/components/body/cartBody.js
src/pages/fileCentricCart/store/cart.js

My Files-Pagination is not working properly

Icdc 2087 and ICDC-2188- My Files-Pagination is not working properly - Remove icon

---

src/components/DataDictionaryComponent/DataDictionary/table/DataDictionaryPropertyTable/DataDictionaryPropertyTable.css

icdc_2236 set table column width

---

graphql/icdc.graphql
graphql/icdc_queries.graphql

apply sample site to filter the case count

ICDC-2252 - apply sample site to filter the case count

---

graphql/icdc.graphql
graphql/icdc_queries.graphql

update query display correct filter options for diagnosis

display correct options for the diagnosis filter

---

graphql/icdc.graphql
graphql/icdc_queries.graphql

-Fixed 'Not Applicable' biobank criteria in filterCaseCountsByBiobank

Fixed biobank filtering error

---

src/bento/dashboardTabData.js
src/components/serverPaginatedTable/components/utils.js
src/pages/caseDetails/caseDetailsView.js
src/pages/dashboardTab/components/tabView.js
src/pages/fileCentricCart/utils.js

set column header on csv download files

Icdc 2257 - set column name on CSV file download

---

graphql/icdc-doc.graphql
graphql/icdc.graphql
graphql/icdc_queries.graphql

-Added Case Count By Study Participation query
-Updated all filtering queries and the search query to include the study participation filter

Multiple Study Participation Filtering

---

graphql/icdc.graphql
graphql/icdc_queries.graphql

Display Case ID, Breed and Diagnosis values for files mapped directly to cases
display Case ID, Breed and Diagnosis values for files mapped directly to cases

Icdc 2260 & 2261 display Case ID, Breed and Diagnosis values for files mapped directly to cases

---

src/bento/dashboardTabData.js
src/bento/tableDownloadCSV.js

set columns for study files download

icdc_2203 set columns for study files download

---

src/pages/programDetail/programDetailView.js
src/pages/studies/studiesView.js
src/pages/study/views/SampleProfile.js
src/utils/utils.js

select correct tab while navigating to dashboard by hyperlink

Icdc 2259 select correct tab while navigating to dashboard by hyperlink

---

src/bento/navigationBarData.js

Data dictionary link verbiage change

link verbiage change

---

src/pages/study/studyDetailView.js

adjust style for pending and embargo icon

icdc_2254 adjust style for pending and embargo icon

---

src/components/SideBar/SideBarComponents/FacetFilters.js

remove search bar item limitation

icdc_2276 display all filter items on the search bar

---

graphql/icdc.graphql
graphql/icdc_queries.graphql

update query to include all the files associated to cases

icdc_2279 update query to include all the files associated to case

---

src/components/SideBar/SideBarComponents/FacetFilters.js

icdc_2276 display all the filter items

---

src/bento/globalStatsData.js

set correct position of program count

icdc_2288 change program count position on globals stats (hot_fix)

---

src/bento/fileCentricCartWorkflowData.js
src/pages/dashboardTab/components/tabView.js
src/pages/fileCentricCart/components/footer/cartFooter.js

1. "download manifest" to "download file manifest"
2. 'Go to Cart' to 'Go to My File'
text update
text update

icdc_2286 and icdc_2287 update text (hot_fix)

---

src/pages/study/studyDetailView.js

icdc_2254 update background color

---

src/pages/dashboardTab/components/tabView.js
src/pages/dashboardTab/dashboard.js

icdc_2290 adjust margin (hot_fix)

---

src/pages/study/studyDetailView.js

icdc_2254 padding adjustment (hot_fix)

---

src/components/serverPaginatedTable/serverPaginatedTable.js

icdc_2278 set correct rowperpage count (hot_fix)

---

src/pages/study/studyDetailView.js

icdc_2254 set background color

---

src/pages/study/views/SampleProfile.js

icdc_2269 code refactor

---

src/components/SideBar/SideBarComponents/CheckBoxView.js

icdc_2253 adjust margin

---

src/components/DataDictionaryComponent/DataDictionary/graph/Canvas/Canvas.jsx

set pop up box to current position

icdc_2319 set pop up box to current position

---

graphql/icdc-doc.graphql
graphql/icdc.graphql
graphql/icdc_queries.graphql

Updated FileDetail query in response to "sample.sample_type" being renamed to "sample.physical_sample_type" in the data

ICDC-2296 Updated sample type property in FileDetail Query

---

src/pages/study/studyDetailController.js

display 404 error page for unmatched accession or study code

icdc_2269 display 404 error page for unmatched accession or study code

---

src/bento/dashboardData.js
src/bento/dashboardTabData.js
src/components/SideBar/SideBarComponents/CheckBoxView.js
src/components/SideBar/SideBarComponents/FacetFilters.js
src/pages/dashboardTab/store/dashboardReducer.js

1. program-specific data sets via the dashboard's facet-driven search functionality
2. add tooltip to program search filter

Icdc 2306 program-specific data sets via the dashboard's facet-driven search functionality

---

src/components/DataDictionaryComponent/DataDictionary/MultiplePDF/Pdf.js
src/components/DataDictionaryComponent/DataDictionary/table/DataDictionaryNode/index.jsx
src/components/DataDictionaryComponent/DataDictionary/table/DataDictionaryTable/DataDictionaryTable.jsx
src/components/DataDictionaryComponent/utils.js

add prefix and date to download PDF file name

icdc_2346 & icdc_2335 add prefix and date to download PDF file name

---

src/components/DataDictionaryComponent/DataDictionary/DataDictionary.jsx

Icdc 2340 set graph view by default

---

package-lock.json
package.json
public/injectEnv.js
src/components/Footer/FooterView.js

icdc_2114 display FS version on Footer

---

src/components/Layout/LayoutView.js

Revert footer

---

src/components/DataDictionaryComponent/DataDictionary/DataDictionary.jsx
src/components/DataDictionaryComponent/DataDictionary/graph/GraphCalculator/GraphCalculator.jsx
src/pages/dashboardTab/store/dashboardReducer.js
src/utils/facetFilters.js

Remove logs

---

package-lock.json
package.json

bento-components package update

bento-components-update

---

src/bento/dashboardData.js
src/components/SideBar/SideBarComponents/FacetFilters.js

ICDC-2397 - expand filters by default

ICDC-2397 - expand filters by default

---

src/pages/studies/InvalidAccesionModal.js

Add missing close button on invalid accession id modal

ICDC-2310-Reopen-1

---

src/bento/landingPageData.js

ICDC-2342-Reopen-1

---

src/bento/aboutPagesRoutes.js
src/bento/navigationBarData.js
src/content/pre-prod/aboutPagesContent.yaml

Icdc 2138 - display "data use" page

---

src/components/DataDictionaryComponent/DataDictionary/graph/GraphNode/GraphNode.jsx

icdc_2419 remove native tooltip

---

src/components/DataDictionaryComponent/DataDictionary/NodePDF/DownloadButton.js
src/components/Layout/utils.js

exclude auto generated props from template

icdc_2404 exclude auto generated props from template

---

src/components/DataDictionaryComponent/DataDictionary/table/DataDictionaryPropertyTable/component/DialogComponent.js
src/components/DataDictionaryComponent/DataDictionary/table/DataDictionaryPropertyTable/component/ListComponent.js

ICDC-2426 Display scroll bar

---

src/components/DataDictionaryComponent/DataDictionary/NodePDF/PdfTableRow.js

update text value for 'Req' column in PDF

icdc_2457 update text value for 'Req' column in PDF

---

src/bento/dataDictionaryData.js
src/components/DataDictionaryComponent/DataDictionary/FacetFilters.js
src/components/DataDictionaryComponent/reducers.js
src/pages/caseDetails/caseDetailsView.js
src/pages/dashboardTab/store/dashboardReducer.js

Selection of model filtering options of one type are not being reflected by the filtering options of other types

Explorer filter fixes

---

src/bento/studiesData.js
src/pages/dashboardTab/components/tabView.js
src/pages/programDetail/programDetailView.js
src/pages/studies/studiesView.js

Display program acronyms within the application-wide study listing as hyperlinks

ICDC-2430 & ICDC-2473

---

src/components/DataDictionaryComponent/DataDictionary/DataModelStructure/DataModelStructure.jsx

display correct graph icon

---

src/components/DataDictionaryComponent/DataDictionary/table/DataDictionaryPropertyTable/component/ListComponent.js

icdc_2426 fix style

---

src/components/DataDictionaryComponent/DataDictionary/NodePDF/DownloadButton.js
src/components/Layout/utils.js

icdc_2404 - exclude autogenerated key from template

---

src/bento/globalFooterData.js

Replace the FNL text block in the footer with the corresponding NCI text block

FNL footer logo to NCI logo text

---

src/components/Footer/FooterView.js
src/content/pre-prod/aboutPagesContent.yaml

Fixed missing image issue & removed console log from footer component.

---

package-lock.json
package.json
public/injectEnv.js

Updating bento-components version to 0.1.106

---

src/bento/JBrowseData.js
src/pages/JbrowseDetail/JbrowseController.js
src/pages/JbrowseDetail/JbrowseDetailView.js

add default session to variant track

icdc_2381 - add default session to variant

---

src/components/SideBar/SideBarComponents/CheckBoxView.js

Revert "Icdc 2409"

---

src/components/serverPaginatedTable/serverPaginatedTable.js

Icdc 2489 set correct page.

---

src/bento/dashboardTabData.js

icdc_2490 display sort icon on sample id column

---

src/bento/dataDictionaryData.js
src/components/DataDictionaryComponent/DataDictionary/DataDictionary.css
src/components/DataDictionaryComponent/DataDictionary/DataDictionary.jsx
src/components/DataDictionaryComponent/DataDictionary/FacetFilters.js

On expanding all Faceted filters in Model Explorer Graph view/Table View blocks the NCI  block  in footer

facet filter overflow and expansion panel fix

---

src/components/DataDictionaryComponent/DataDictionary/DataDictionary.jsx

remove facets

---

src/content/dev/aboutPagesContent.yaml
src/content/pre-prod/aboutPagesContent.yaml
src/content/prod/aboutPagesContent.yaml
src/content/qa/aboutPagesContent.yaml
src/content/stage/aboutPagesContent.yaml

Icdc news page props

---

src/content/dev/aboutPagesContent.yaml
src/content/pre-prod/aboutPagesContent.yaml
src/content/prod/aboutPagesContent.yaml
src/content/qa/aboutPagesContent.yaml
src/content/stage/aboutPagesContent.yaml

Prod-deplyment - update aboutPage

---

graphql/icdc-doc.graphql
graphql/icdc.graphql
graphql/icdc_queries.graphql
src/bento/studiesData.js
src/pages/studies/studiesView.js
src/pages/study/utils.js

End User views data availability landscape via study listings

data avail-landscape tentative

---

src/bento/globalFooterData.js

Add Vulnerability Disclosure link to footer

Add Vulnerability Disclosure link to footer

---

src/bento/globalFooterData.js
src/components/DataDictionaryComponent/DataDictionary/DataDictionary.jsx

Merging v3.21.3.1 to Develop

---

src/components/GridWithFooter/tableThemeConfig.js
src/components/Layout/LayoutView.js
src/pages/dashboardTab/dashboard.js
src/pages/fileCentricCart/components/body/cartTableThemeConfig.js
src/pages/fileCentricCart/components/footer/cartFooter.style.js
src/pages/programs/programsView.js
src/pages/studies/studiesMuiThemConfig.js

margin-fix

---

package-lock.json
package.json
src/store/index.js

Model Explorer - Facet filter refactor

---

src/pages/dashboardTab/dashboard.js

padding fix

---

src/content/pre-prod/aboutPagesContent.yaml

Removing Matthew Beyers from "About" pages

remove Matthew Beyers

---

src/bento/JBrowseData.js

set default assembly as camfam 3

Icdc 2575 set default assembly

---

package-lock.json
package.json
src/bento/dataDictionaryData.js
src/components/Layout/utils.js

gen3 code migration

---

package-lock.json
package.json
src/components/Layout/utils.js

model-explorer version update

---

package-lock.json
package.json

update model-explorer version for icdc_2513

---

src/pages/landing/landingController.js
src/pages/landing/landingView.js
src/pages/landing/views/widgets.js

Upadate landingView spotlight styles to match invision design

---

src/pages/programDetail/programDetailView.js

- The "Under Embargo" and "Pending" UI flag within study listings is no longer being applied

ICDC-2568-II

---

src/pages/programDetail/programDetailView.js

- Implement fixes for ICDC-2566 & ICDC-2570 on the programDetail page.

ICDC-2566-2570-program-details

---

package-lock.json
package.json

ICDC-2625 - update ME versoin

---

src/bento/JBrowseData.js

jbrowse - set correct url

---

package-lock.json
package.json

bento-components update

---

package-lock.json
package.json

update ME version

---

package-lock.json
package.json
public/injectEnv.js
src/bento/dataDictionaryData.js
src/components/Layout/utils.js

Filter by inclusion & section facet sorting configuration

---

package-lock.json
package.json

Display values of the "Labeled" tag within the data model explorer's Table View and PDF exports
Model-explorer

ICDC-2590/labeled-tag-ui-pdf

---

DAL-config-doc.md

DAL-documentation

---

package-lock.json
package.json

model-explorer update

---

package-lock.json
package.json
src/bento/dataDictionaryData.js

filter by uiDisplay & show filter expansion

---

package-lock.json
package.json

dependacy update

---

package-lock.json
package.json

update model-explorer to v0.0.48

---

public/injectEnv.js
src/pages/landing/landingController.js

Change source of code for ICDC Static Content

static content env variables

---

graphql/icdc.graphql
graphql/icdc_queries.graphql

This query was updated after ES changes, so need to be updated again.

Reverse volumeOfData query that had been overwritten due to old branch

---

package-lock.json
package.json

ME version update

---

src/bento/dashboardTabData.js
src/pages/dashboardTab/store/dashboardReducer.js

On the DEV tier, the Dashboard fails to display any data after navigating there via hyperlinked case and sample counts

ICDC-2749: fixed dashboard fails on hyperlink from sample or case

---

package-lock.json
package.json

set ME version

---

public/injectEnv.js

Change source of code for ICDC About page

ICDC-2572: about pages pull content from static repo

---

src/pages/fileCentricCart/cartController.js
src/pages/fileCentricCart/cartView.js

refresh table after delete

---

src/pages/dashboardTab/components/tabView.js

set link style

---

src/pages/dashboardTab/store/dashboardReducer.js

Elasticsearch: Unable to add files to cart.

ICDC-2767: fix add all files to cart

---

.gitignore
src/bento/dashboardTabData.js
src/components/serverPaginatedTable/serverPaginatedTable.js
src/pages/dashboardTab/components/tabController.js
src/pages/dashboardTab/components/tabView.js
src/pages/dashboardTab/store/dashboardReducer.js

ES explore table fixes

---

src/pages/dashboardTab/components/tabView.js

ICDC-2499: multiStudy tooltip fix

---

src/pages/dashboardTab/components/tabView.js

Fix link style

---

src/pages/dashboardTab/components/tabThemeConfig.js

link style fix

---

src/pages/dashboardTab/components/tabView.js

remove class

---

src/bento/tableDownloadCSV.js
src/components/serverPaginatedTable/components/CSVDownloadCustomToolbar.js
src/components/serverPaginatedTable/serverPaginatedTable.js

cvs download fix

---

package-lock.json
package.json
src/components/Layout/utils.js

add readMe dialog component

---

src/pages/study/views/SampleProfile.js

change sample count color

---

src/bento/JBrowseData.js
src/pages/JbrowseDetail/components/JBrowseViewBtn.js

Set font style for Jbrowse Tooltip

Set font style for Jbrowse Tooltip

---

public/injectEnv.js
src/components/Layout/utils.js

Change source of code for ICDC ReadMe content

update readMe endpoint

---

public/injectEnv.js

ICDC-2856-II

---

.eslintrc.js
config/webpack.config.js
package-lock.json
package.json

configure webpack 4 to parsing optional chaining

---

package-lock.json
package.json
src/components/Layout/utils.js

set redux for reactflow

---

package-lock.json
package.json

update ME versoin

---

src/bento/globalFooterData.js
src/components/Footer/FooterView.js

Footer displays incorrect text and embeds incorrect link

fix footer

---

package-lock.json
package.json

update bento-components package

---

package-lock.json
package.json
src/components/Layout/utils.js

update dmn version

---

src/bento/globalFooterData.js

Privacy Policy for landing page footer

Privacy footer modal

---

src/pages/programDetail/programDetailView.js

- View real-time supplementary data for ICDC studies on the Program Details page

Integrate interOp api into programDetail page

---

package-lock.json
package.json
src/components/Footer/FooterView.js
src/components/NavBar/NavBarView.js
src/pages/JbrowseDetail/JbrowseDetailView.js

JBrowse session windows don't support navigation

remove jBrowse navigation

---

src/pages/JbrowseDetail/JbrowseDetailView.js

remove css

---

src/bento/JBrowseData.js

Update the track ID for the new liftover track so that it is non-ambiguous.

Update track ID

---

src/pages/study/studyDetailView.js
src/pages/study/views/supporting-data/supportingData.js

refactor supporting data tab

---

src/pages/study/studyDetailView.js
src/pages/study/views/supporting-data/supportingData.js

Improve supporting data tab in studyDetails page

Icdc 2982 ii

---

package-lock.json
package.json

update DMN to v1.0.84

---

graphql/icdc-doc.graphql
graphql/icdc.graphql
graphql/icdc_queries.graphql
src/pages/study/views/supporting-data/supportingData.js

- add `drs_prefix` constant and `drs_uri` return to `filesInList`/`filesInListDesc` queries

add DRS URIs to return of filesInList queries (ICDC-3029)

---

graphql/icdc.graphql
graphql/icdc_queries.graphql

- add passthrough to clinical data node queries so they can be run from w/in FE codebase

add passthrough to clinical data node queries

---

public/injectEnv.js
src/pages/fileCentricCart/components/header/cartHeader.js

FileCentric cart readMe improvement

integrate read me content repo fileCart readMe into frontend

---

src/components/sideBarFilter/BentoFacetFilter.js

revert change

---

src/bento/studyDetailsData.js

Update clinical data csv queries

clinical data csv fix

---

src/pages/fileCentricCart/components/header/cartHeader.js

hide CGC button

---

src/pages/programDetail/programDetailView.js

The Data Availability Landscape incorrectly indicates that the GLIOMA01 study has study files associated with it

fix DAL on programDetails view

---

src/pages/JbrowseDetail/JbrowseDetailView.js
src/pages/JbrowseDetail/components/JBrowseViewBtn.js
src/pages/fileCentricCart/cartView.style.js

fix button styles

---

src/pages/study/views/clinical-data/clinicalData.js

Remove "Download All" button from Clinical Observations tab

remove download all btn

---

package-lock.json
package.json

Data ->Model Navigator->Texts are overlapping when we do search in Filter& Search textbox

update dmn to 1.0.89

---

src/pages/dashboardTab/components/modal.js
src/pages/dashboardTab/store/dashboardReducer.js

Case Files tab-All filtered files button is not adding all files

add all files case files tab

---

src/components/ReadMeDialog/ReadMe.component.js
src/pages/fileCentricCart/utils.js

fileCentricCart pdf download fix

ICDC-3185 & ICDC-3187

---

src/components/PaginatedTable/Customize/TableView.js

Icdc 3110 - Case tab add all files button

---

src/components/PaginatedTable/Customize/PaginationOptions.js

revert dead code

---

package-lock.json
package.json

upgrade dmn to 1.0.94

---

src/bento/localSearchData.js

increased number of suggested list

---

package-lock.json
package.json

Updated `data-model-naviagtor` to `v1.0.95`

updated DMN to v1.0.95

---

src/pages/study/views/StudyFiles.js

File Association column "Study" needs to be changed to "study"

change to lowercase

---

src/components/sideBarFilter/BentoFacetFilter.js

Icdc 3292-Fixed tooltip text

---

src/components/Tab/Tab.js
src/pages/study/studyDetailView.js
src/pages/study/studyDetailsStyle.js
src/pages/study/views/supporting-data/supportingData.js

Icdc 3197-Completed Figma comments.

---

src/pages/fileCentricCart/header/cartHeader.js
src/pages/fileCentricCart/header/cartHeader.style.js

Implement updated design for "My Files" Cart page

fileCentricCart header redesign

---

src/pages/fileCentricCart/header/downloadFileManifestDialog.js

Make close icon on download manifest button consistent

fix close icon

---

src/pages/fileCentricCart/Theme.js
src/pages/fileCentricCart/header/cartHeader.style.js

2023 Q2 Final Design QA: Supporting Data

design qa file-centric-cart

---

package-lock.json
package.json
src/pages/fileCentricCart/header/cartHeader.js
src/pages/fileCentricCart/header/cartHeader.style.js

upgrade dmn to v 1.1.1

---

src/pages/dashboard/filterQueryBar/QueryBarStyles.js

Icdc 3309 - Resolved the Querybar box spacing issue.

---

`
src/bento/navigationBarData.js
src/components/Layout/LayoutView.js

Icdc 3312 - Completed Nabar exclusion

---

src/components/sideBarFilter/BentoFacetFilter.js

Icdc 3292 - Removed a period from the question mark icon tooltip in UploadModal

---

src/components/sideBarFilter/BentoFacetFilter.js

Disable filter in unifiedview page

---

package-lock.json
package.json

resolve dependency

---

src/pages/fileCentricCart/header/cartHeader.js
src/pages/fileCentricCart/header/cartHeader.style.js

Implement updated design for "My Files" Cart page

dropdown btn fixes

---

src/bento/caseDetailsData.js
src/components/DataAvailabilityTable/tableThemeConfig.js
src/pages/caseDetails/SampleView/Theme.js
src/pages/programDetail/programDetailView.js
src/pages/studies/studiesView.js

Adjust padding

---

package-lock.json
package.json

update dmn to version 1.1.15

---

src/utils/colors.js

set correct colors

---

src/pages/study/studyDetailView.js

remove breadcrumb

---

src/bento/studiesData.js
src/components/DataAvailabilityTable/StudiesTable.js
src/pages/studies/studiesView.js

Studies page - set no of row per page to 25

---

package-lock.json
package.json
public/index.html

Update data-model-navigator to v1.1.16

update dmn to v1.1.16

---

src/content/pre-prod/aboutPagesContent.yaml

- remove extra hyphen at end of `/pre-prod/aboutPageContent.yaml` and format

Format about page yaml

---

src/content/pre-prod/aboutPagesContent.yaml

remove hyphen

---

package-lock.json
package.json
public/index.css
src/components/ReadMeDialog/ReadMe.component.js
src/pages/fileCentricCart/header/cartHeader.js
src/pages/fileCentricCart/header/cartHeader.style.js

Cart header qa

---

src/bento/dashboardData.js

update widget config

---

src/pages/study/studyDetailView.js

The "Cases" and "Associated Cases" hyperlinks improperly redirects User

scenario 2

---

src/pages/study/views/clinical-data/clinicalData.js

2023 Q2 Final Design QA: Clinical Data

ICDC-3198-II

---

src/components/sideBarFilter/BentoFacetFilter.js

add undefined check

---

src/pages/study/views/clinical-data/clinicalData.js

2023 Q2 Final Design QA: Clinical Data

center csv column

---

src/bento/localSearchData.js

increase search field

---

src/pages/study/views/clinical-data/components/downloadBtn.js

line height change

---

package-lock.json
package.json

revert compatible version

---

package-lock.json
package.json

update dmn to 1.1.23

---

package-lock.json
package.json
src/components/ReadMeDialog/ReadMe.component.js

page break

---

src/pages/globalSearch/card/model/ModelCardView.js

search set to lower case

---

src/components/ReadMeDialog/ReadMe.component.js

page break setting

---

package-lock.json

revert package log
